version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
    container_name: cloud-laravel-app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # db:
  #   image: mysql:8
  #   container_name: mysql-db
  #   environment:
  #     MYSQL_DATABASE: db_sispak_cloud
  #     MYSQL_ROOT_PASSWORD: root 
  #     MYSQL_USER: cloud-app
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - laravel

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
